global:
  scrape_timeout: 180s
  min_interval: 90s
  max_connections: 10
  max_idle_connections: 10

jobs:
  - job_name: mssql
    static_configs:
      - targets:
          'sqlserver://sa:5555P@55w0rd@0.0.0.0:1433'
        labels:
          sql_instance: 'localhost'

collectors:
  # A collector defining standard metrics for Microsoft SQL Server.
  - collector_name: mssql_standard
    metrics:
      - metric_name: mssql_server_name
        type: gauge
        help: 'Servername test.'
        key_labels:
          - servername
        values: 
          - abc
        query: |
          SELECT 'hello' AS servername, 1 AS abc

      - metric_name: mssql_log_growths
        type: counter
        help: 'Total number of times the transaction log has been expanded since last restart, per database.'
        key_labels:
          - db
        values: [counter]
        query: |
          SELECT rtrim(instance_name) AS db, cntr_value AS counter
          FROM sys.dm_os_performance_counters
          WHERE counter_name = 'Log Growths' AND instance_name <> '_Total'
      # A different metric, with multiple values produced from each result row.
      - metric_name: mssql_io_stall_seconds
        type: counter
        help: 'Stall time in seconds per database and I/O operation.'
        key_labels:
          # Populated from the `db` column of the result.
          - db
        value_label: operation
        values:
          - io_stall_read
          - io_stall_write
        query_ref: io_stall

      # Another metric, uses same named query (referenced through query_ref) as mssql_io_stall_seconds.
      - metric_name: mssql_io_stall_total_seconds
        type: counter
        help: 'Total stall time in seconds per database.'
        key_labels:
          # Populated from the `db` column of the result.
          - db
        # Only one value, populated from the `io_stall` column.
        values:
          - io_stall
        query_ref: io_stall

    # Named queries, referenced by one or more metrics, through query_ref.
    queries:
      # Populates `mssql_io_stall` and `mssql_io_stall_total`
      - query_name: io_stall
        query: |
          SELECT
            cast(DB_Name(a.database_id) as varchar) AS db,
            sum(io_stall_read_ms) / 1000.0 AS io_stall_read,
            sum(io_stall_write_ms) / 1000.0 AS io_stall_write,
            sum(io_stall) / 1000.0 AS io_stall
          FROM
            sys.dm_io_virtual_file_stats(null, null) a
          INNER JOIN sys.master_files b ON a.database_id = b.database_id AND a.file_id = b.file_id
          GROUP BY a.database_id